# Gestione button statistiche ed impostazioni della card 
input_boolean: 
  statistic_ac_salone: 

input_select: 
  setting_card_ac_salone:
    name: setting_card_ac_salone
    options:
      - "off"
      - "1"
      - "2"
      - "3"
      - "4"

automation:
- id: gestione_pulsanti_card_ac_salone
  alias: Gestione pulsanti card ac_salone
  trigger:
  - platform: state
    entity_id:  input_boolean.statistic_ac_salone
    to: 'on'
  - platform: state
    entity_id: input_select.setting_card_ac_salone
    not_to: 'off'
  action:
  - if: "{{trigger.entity_id == 'input_boolean.statistic_ac_salone'}}"
    then:
        - service: input_select.select_option
          target:
            entity_id: input_select.setting_card_ac_salone
          data:
            option: 'off'
    else:
        - service: input_boolean.turn_off
          target:
            entity_id: input_boolean.statistic_ac_salone